
- hosts: 127.0.0.1
  become: yes

  tasks:
    - name: install Pip
      apt:
        state: latest
        name: python-pip

    - name: install Docker Python lib
      pip:
        name:
          - docker
          - requests>=2.20.1

    - name: Init a new swarm with default parameters
      docker_swarm:
        state: present

    - name: Start Swarm Docker Registry
      docker_swarm_service:
        name: registry
        image: registry:2
        publish:
          - published_port: 5000
            target_port: 5000
